# Generated by Django 5.0.1 on 2024-02-18 07:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient_Data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cr_number', models.CharField(max_length=50, unique=True)),
                ('reg_date', models.DateField()),
                ('full_name', models.CharField(max_length=120)),
                ('p_age', models.IntegerField(null=True)),
                ('p_gender', models.CharField(max_length=200, null=True)),
                ('p_height', models.IntegerField(null=True)),
                ('p_weight', models.IntegerField(null=True)),
                ('phone_number', models.CharField(max_length=20, null=True, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+999999999'.", regex='^\\+?1?\\d{10,13}$')])),
                ('p_email', models.EmailField(max_length=254, null=True, unique=True)),
                ('p_address', models.TextField(max_length=200, null=True)),
                ('ecog', models.TextField(null=True)),
                ('comborbidity', models.TextField(null=True)),
                ('p_id_type', models.TextField(null=True)),
                ('p_id_no', models.CharField(max_length=100, null=True, unique=True)),
                ('relative_name', models.CharField(max_length=200, null=True)),
                ('p_relationship', models.CharField(max_length=200, null=True)),
                ('smoking_duration', models.CharField(default='UNK', max_length=200, null=True)),
                ('tobacco_use', models.CharField(default='UNK', max_length=200, null=True)),
                ('alcohol_use', models.CharField(default='UNK', max_length=200, null=True)),
                ('notes', models.TextField(null=True)),
            ],
        ),
    ]
