# Generated by Django 5.0.1 on 2024-02-18 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OncFlow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient_data',
            name='phone_number',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='patient_data',
            name='reg_date',
            field=models.CharField(max_length=12),
        ),
    ]
